name: Test Deltakit-Stim

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

concurrency:
  group: fast-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cpp_unit_tests:
    name: Run Deltakit-Stim C++ unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out main code
        uses: actions/checkout@v5
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Build and run unit tests on Linux
        if: runner.os == 'Linux'
        run: |
          bazel build //:stim_test
          bazel run //:stim_test
      - name: Build and run unit tests on macOS
        if: runner.os == 'macOS'
        run: |
          bazel build //:stim_test
          bazel run //:stim_test --test_filter=-"match_graph_drawer_3d.*:circuit_diagram_timeline_3d*"
